[package]
name = "diem-secure-net"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
repository = "https://github.com/diem/diem"
description = "Diem's Simple Network Substrate"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
once_cell = "1.4.1"
serde = { version = "1.0.117", features = ["rc"], default-features = false }
thiserror = "1.0.22"

diem-logger = { path = "../../common/logger", version = "0.1.0" }
diem-secure-push-metrics = { path = "../../secure/push-metrics", version = "0.1.0" }
diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }

[dev-dependencies]
diem-config = { path = "../../config", version = "0.1.0" }
