[package]
name = "storage-client"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem storage client"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
serde = "1.0.123"

bcs = "0.1.2"
diem-crypto = { path = "../../crypto/crypto", version = "0.1.0" }
diem-logger = { path = "../../common/logger", version = "0.1.0" }
diem-infallible = { path = "../../common/infallible", version = "0.1.0" }
diem-secure-net = { path = "../../secure/net", version = "0.1.0" }
diem-types = { path = "../../types", version = "0.1.0" }
diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }
storage-interface = { path = "../storage-interface", version = "0.1.0" }

[features]
default = []
