[package]
name = "storage_client"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = { version = "0.3.0-alpha.13", package = "futures-preview", features = ["compat"] }
futures_01 = { version = "0.1.25", package = "futures" }
grpcio = "0.4.4"

crypto = { path = "../../crypto/legacy_crypto" }
canonical_serialization = { path = "../../common/canonical_serialization" }
failure = { path = "../../common/failure_ext", package = "failure_ext" }
proto_conv = { path = "../../common/proto_conv" }
scratchpad = { path = "../scratchpad" }
storage_proto = { path = "../storage_proto" }
state_view = { path = "../state_view" }
types = { path = "../../types" }
