base:
    # This is the location Libra will store its database. It is backed by a dedicated docker volume
    # for persistence.
    data_dir: "/opt/libra/data"
    role: "full_node"
    waypoint:
        # This is a checkpoint into the blockchain for added security.
        from_file: "/opt/libra/etc/waypoint.txt"

execution:
    # Path to a genesis transaction. Note, this must be paired with a waypoint. If you update your
    # waypoint without a corresponding genesis, the file location should be an empty path.
    genesis_file_location: "/opt/libra/etc/genesis.blob"

full_node_networks:
      # Disabled for testnet
    - discovery_method: "none"
      # The network must have a listen address to specify protocols. This runs it locally to
      # prevent remote, incoming connections.
      listen_address: "/ip4/127.0.0.1/tcp/6180"
      network_id: "public"
      # Testnet does not have the right discovery entry points on-chain so this is used instead
      seed_addrs:
          4223dd0eeb0b0d78720a8990700955e1:
              - "/dns4/fn.testnet.libra.org/tcp/6182/ln-noise-ik/b6fd31624af370085cc3f872437bb4d9384b31a11b33b9591ddfaaed5a28b613/ln-handshake/0"

rpc:
    # This specifies your JSON-RPC endpoint. Intentionally on public so that Docker can export it.
    address: 0.0.0.0:8080

# Do not modify this value as it dictates upstream peers, those which receive outgoing transactions
# and funnel downward the latest blockchain state.
upstream:
    networks:
        - public
