version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker/"
    schedule:
      interval: "daily"
    labels:
      - "docker"
      - "dependencies"
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "github-actions"
      - "dependencies"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "cargo"
      - "dependencies"
    ignore:
      - dependency-name: "codespan*"
      - dependency-name: "libfuzzer-sys"
      - dependency-name: "bindgen"
    open-pull-requests-limit: 0
