version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    allow:
      # The undocumented default is to open prs for only direct dependencies.
      - dependency-type: all
    schedule:
      interval: "daily"
    labels:
      - "cargo"
      - "dependencies"
    ignore:
      - dependency-name: "codespan*"
      - dependency-name: "libfuzzer-sys"
      - dependency-name: "bindgen"
    open-pull-requests-limit: 20

  # Dockerfiles.

  - package-ecosystem: "docker"
    directory: "/docker/ci/alpine"
    schedule:
      interval: "daily"
    labels:
      - "docker"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/docker/ci/arch"
    schedule:
      interval: "daily"
    labels:
      - "docker"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/docker/ci/centos"
    schedule:
      interval: "daily"
    labels:
      - "docker"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/docker/ci/circleci"
    schedule:
      interval: "daily"
    labels:
      - "docker"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/docker/client"
    schedule:
      interval: "daily"
    labels:
      - "docker"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/docker/cluster-test"
    schedule:
      interval: "daily"
    labels:
      - "docker"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/docker/init"
    schedule:
      interval: "daily"
    labels:
      - "docker"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/docker/logstash"
    schedule:
      interval: "daily"
    labels:
      - "docker"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/docker/mint"
    schedule:
      interval: "daily"
    labels:
      - "docker"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/docker/safety-rules"
    schedule:
      interval: "daily"
    labels:
      - "docker"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/docker/tools"
    schedule:
      interval: "daily"
    labels:
      - "docker"
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/docker/validator"
    schedule:
      interval: "daily"
    labels:
      - "docker"
      - "dependencies"

  # Github Actions

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "github-actions"
      - "dependencies"
