[package]
name = "diem-nibble"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem diem-nibble"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
diem-workspace-hack = { path = "../workspace-hack", version = "0.1.0" }
proptest = { version = "0.10.1", optional = true }
serde = { version = "1.0.120", features = ["derive"] }

[features]
default = []
fuzzing = ["proptest"]
