[package]
name = "x"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem extended cargo tasks"
edition = "2018"
publish = false
license = "Apache-2.0"

[dependencies]
determinator = "0.1.1"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.60"
structopt = "0.3.21"
anyhow = "1.0.34"
colored-diff = "0.2.2"
guppy = { version = "0.6.2", features = ["summaries"] }
indoc = "1.0.3"
toml = "0.5.7"
env_logger = "0.8.2"
log = "0.4.11"
chrono = "0.4.19"
globset = "0.4.6"
regex = "1.4.2"
rayon = "1.5.0"
indexmap = "1.6.0"
x-core = { version = "0.1.0", path = "../x-core" }
x-lint = { version = "0.1.0", path = "../x-lint" }
diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }
