[package]
name = "move-lang-test-utils"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
edition = "2018"
publish = false
license = "Apache-2.0"

[dependencies]
datatest-stable = { path = "../../../common/datatest-stable" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }
