[package]
name = "ir-testsuite"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem functional tests"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
edition = "2018"

[dev-dependencies]
anyhow = "1.0.34"
bytecode-verifier = { path = "../bytecode-verifier", version = "0.1.0" }
datatest-stable = { path = "../../common/datatest-stable", version = "0.1.0" }
functional-tests = { path = "../testing-infra/functional-tests", version = "0.1.0" }
ir-to-bytecode = { path = "../compiler/ir-to-bytecode", version = "0.1.0" }
diem-types = { path = "../../types", version = "0.1.0" }
diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }
move-ir-types = { path = "../move-ir/types", version = "0.1.0" }
compiled-stdlib = { path = "../stdlib/compiled",  version = "0.1.0" }
vm = { path = "../vm", version = "0.1.0" }


[[test]]
name = "testsuite"
harness = false
