[package]
name = "vm"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra vm"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
byteorder = "1.3.2"
hex = "0.3.2"
lazy_static = "1.3.0"
mirai-annotations = "1.4.0"
proptest = "0.9"
proptest-derive = "0.1.1"
serde = { version = "1", features = ["derive"] }
lcs = { path = "../../common/lcs", version = "0.1.0", package = "libra-canonical-serialization" }
libra-crypto = { path = "../../crypto/crypto", version = "0.1.0" }
failure = { path = "../../common/failure-ext", version = "0.1.0", package = "libra-failure-ext" }
libra-proptest-helpers = { path = "../../common/proptest-helpers", version = "0.1.0" }
libra-types = { path = "../../types", version = "0.1.0" }

[dev-dependencies]
serde_json = "1"
libra-types = { path = "../../types", version = "0.1.0", features = ["testing"]}

[features]
default = []
mirai-contracts = []
testing = ["libra-types/testing"]
