[package]
name = "diem-workspace-hack"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem workspace hack"
repository = "https://github.com/libra/libra"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bytes = { version = "0.5.6", features = ["serde", "std"] }
cc = { version = "1.0.66", features = ["jobserver", "parallel"] }
log = { version = "0.4.11", features = ["serde", "std"] }
memchr = { version = "2.3.4", features = ["std", "use_std"] }
num-traits = { version = "0.2.14", features = ["std"] }
petgraph = { version = "0.5.1", features = ["graphmap", "matrix_graph", "stable_graph"] }
serde = { version = "1.0.117", features = ["derive", "rc"] }
sha-1 = { version = "0.9.2", features = ["std"] }
subtle = { version = "2.3.0", features = ["i128", "std"] }
syn = { version = "1.0.53", features = ["clone-impls", "derive", "extra-traits", "fold", "full", "parsing", "printing", "proc-macro", "quote", "visit", "visit-mut"] }
