[package]
name = "stdlib"
version = "0.1.0"
edition = "2018"
authors = ["Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false

[dependencies]
compiler = { path = "../compiler" }
types = { path = "../../types" }
lazy_static = "1.3.0"
