[package]
name = "storage-proto"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra storage proto"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bytes = "0.4.12"
futures = "0.1.28"
grpcio = { version = "=0.5.0-alpha.4", default-features = false, features = ["prost-codec"] }
proptest = "0.9.2"
proptest-derive = "0.1.0"
prost = "0.5.0"

libra-crypto = { path = "../../crypto/crypto", version = "0.1.0" }
failure = { path = "../../common/failure-ext", version = "0.1.0", package = "libra-failure-ext" }
libra-types = { path = "../../types", version = "0.1.0" }

[build-dependencies]
grpcio-compiler = { version = "0.5.0-alpha.2", default-features = false, features = ["prost-codec"] }

[dev-dependencies]
libra-types = { path = "../../types", version = "0.1.0", features = ["testing"]}
libra-prost-ext = { path = "../../common/prost-ext", version = "0.1.0" }
