[package]
name = "diemsum"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem diemdb data access tool for data analysis or human read"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
structopt = "0.3.21"
serde = "1.0.123"
serde_json = "1.0.61"

diemdb = { path = "../diemdb", version = "0.1.0", features = ["diemsum"] }
diem-crypto = { path = "../../crypto/crypto", version = "0.1.0" }
diem-types = { path = "../../types", version = "0.1.0" }
diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }
storage-interface = { path = "../storage-interface", version = "0.1.0" }
