[package]
name = "sparse_merkle"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bincode = "1.1.1"

crypto = { path = "../../crypto/legacy_crypto" }
failure = { path = "../../common/failure_ext", package = "failure_ext" }
serde = { version = "1.0.89", features = ["derive"] }
types = { path = "../../types" }

[dev-dependencies]
proptest = "0.9"
rand = "0.6.5"
serde_test = "1.0.87"
