[package]
name = "netcore"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem netcore"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bytes = "1.0.1"
futures = "0.3.12"
pin-project = "1.0.4"
serde = { version = "1.0.120", default-features = false }
tokio = { version = "1.0.2", features = ["full"] }
tokio-util = { version = "0.6.0", features = ["compat"] }
url = { version = "2.1.1" }

diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }
diem-network-address = { path = "../network-address", version = "0.1.0" }
diem-types = { path = "../../types" }
memsocket = { path = "../memsocket", version = "0.1.0", optional = true }
proxy = { path = "../../common/proxy" }

[dev-dependencies]
diem-logger = { path = "../../common/logger", version = "0.1.0" }
diem-network-address = { path = "../network-address", version = "0.1.0", features = ["fuzzing"] }
memsocket = { path = "../memsocket", version = "0.1.0" }

[features]
default = []
fuzzing = ["memsocket/fuzzing"]
testing = ["memsocket/testing"]
