[package]
name = "functional_tests"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
compiler = { path = "../compiler" }
failure = { path = "../../common/failure_ext", package = "failure_ext" }
types = { path = "../../types" }
vm = { path = "../vm" }
bytecode_verifier = { path = "../bytecode_verifier" }
vm_runtime_tests = { path = "../vm/vm_runtime/vm_runtime_tests" }
config = { path = "../../config" }
termcolor = "1.0.4"
filecheck = "0.4.0"
datatest = "0.3.1"
lazy_static = "1.3.0"
regex = "1.1.6"
