[package]
name = "move-package"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
petgraph = "0.5.1"
anyhow = "1.0.40"
walkdir = "2.3.1"
structopt = "0.3.21"
bcs = { git = "https://github.com/diem/bcs", rev = "30ce9f4ac51342d2fb4c04c4f5b40683d9652dc6" }
colored = "2.0.0"
serde_yaml = "0.8.17"
checksumdir = "0.3.0"
tempfile = "3.2.0"

diem-workspace-hack = { path = "../../../crates/diem-workspace-hack" }
move-binary-format = { path = "../../move-binary-format" }
move-lang = { path = "../../move-lang" }
bytecode-source-map = { path = "../../compiler/bytecode-source-map" }
abigen = { path = "../../move-prover/abigen" }
docgen = { path = "../../move-prover/docgen" }
errmapgen = { path = "../../move-prover/errmapgen" }
move-core-types = { path = "../../move-core/types" }
move-symbol-pool = { path = "../../move-symbol-pool" }
move-command-line-common = { path = "../../move-command-line-common" }

[dev-dependencies]
datatest-stable = "0.1.1"

[[test]]
name = "test_runner"
harness = false
