[package]
name = "move-prover-test-utils"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
prettydiff = "0.3.1"
anyhow = "1.0.34"
regex = "1.4.2"
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
