[package]
name = "subscription-service"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem subscription service"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"

diem-types = { path = "../../types", version = "0.1.0" }
diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }
channel = { path = "..//channel", version = "0.1.0" }
