[package]
name = "vm-runtime-types"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra vm runtime types"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bit-vec = "0.6.1"
lazy_static = "1.3.0"
proptest = "0.9"
sha2 = "0.8.0"
serde = { version = "1.0", features = ["derive", "rc"] }
libra-types = { path = "../../../../types", version = "0.1.0" }
vm = { path = "../../", version = "0.1.0" }
lcs = { path = "../../../../common/lcs", version = "0.1.0", package = "libra-canonical-serialization" }
libra-crypto = { path = "../../../../crypto/crypto", version = "0.1.0" }
failure = { path = "../../../../common/failure-ext", version = "0.1.0", package = "libra-failure-ext" }

[dev-dependencies]
libra-types = { path = "../../../../types", version = "0.1.0", features = ["testing"] }
vm = { path = "../../", version = "0.1.0", features = ["testing"]}

[features]
instruction_synthesis = []
testing = ["libra-types/testing"]
