[package]
name = "diem-wallet"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem wallet"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
rand = "0.8.3"
hex = "0.4.2"
hmac = "0.10.1"
byteorder = "1.4.2"
pbkdf2 = "0.7.3"
serde = "1.0.123"
sha2 = "0.9.3"
thiserror = "1.0.24"
ed25519-dalek = { version = "0.1.0", package = "ed25519-dalek-fiat", default-features = false, features = ["std", "fiat_u64_backend"] }
diem-crypto = { path = "../../../crypto/crypto", version = "0.1.0", features = ["fuzzing"] }
diem-temppath = { path = "../../../common/temppath/", version = "0.1.0" }
diem-types = { path = "../../../types", version = "0.1.0" }
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
mirai-annotations = "1.10.1"

[features]
default = []
fuzzing = ["diem-types/fuzzing"]
