[package]
name = "state-sync-v1"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem state synchronizer v1 (state sync v1)"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bcs = { git = "https://github.com/diem/bcs", rev = "30ce9f4ac51342d2fb4c04c4f5b40683d9652dc6" }
fail = "0.4.0"
futures = "0.3.12"
itertools = { version = "0.10.0", default-features = false }
once_cell = "1.7.2"
proptest = { version = "1.0.0", optional = true }
rand = "0.8.3"
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"
tokio = { version = "1.8.1", features = ["full"] }
tokio-stream = "0.1.4"

consensus-notifications = { path = "../inter-component/consensus-notifications" }
channel = { path = "../../crates/channel" }
diem-config = { path = "../../config" }
diem-crypto = { path = "../../crates/diem-crypto" }
diem-infallible = { path = "../../crates/diem-infallible" }
diem-logger = { path = "../../crates/diem-logger" }
diem-mempool = { path = "../../mempool"}
diem-metrics = { path = "../../crates/diem-metrics" }
diem-proptest-helpers = { path = "../../crates/diem-proptest-helpers", optional = true }
diem-temppath = { path = "../../crates/diem-temppath" }
diem-types = { path = "../../types" }
diem-vm = { path = "../../language/diem-vm" }
diem-workspace-hack = { path = "../../crates/diem-workspace-hack" }
diemdb = { path = "../../storage/diemdb", optional = true }
executor = { path = "../../execution/executor" }
executor-test-helpers = { path = "../../execution/executor-test-helpers", optional = true }
executor-types = { path = "../../execution/executor-types" }
memsocket = { path = "../../network/memsocket", optional = true }
mempool-notifications = { path = "../inter-component/mempool-notifications" }
netcore = { path = "../../network/netcore" }
network = { path = "../../network" }
storage-interface = { path = "../../storage/storage-interface" }
subscription-service = { path = "../../crates/subscription-service" }
vm-genesis = { path = "../../language/tools/vm-genesis", optional = true }

[dev-dependencies]
bytes = "1.0.1"
proptest = "1.0.0"

consensus-notifications = { path = "../inter-component/consensus-notifications" }
channel = { path = "../../common/channel" }
diem-framework-releases= { path = "../../language/diem-framework/releases" }
diem-crypto = { path = "../../crates/diem-crypto" }
diem-genesis-tool = {path = "../../config/management/genesis", features = ["testing"] }
diem-mempool = { path = "../../mempool", features = ["fuzzing"] }
diemdb = { path = "../../storage/diemdb" }
executor-test-helpers = { path = "../../execution/executor-test-helpers" }
memsocket = { path = "../../network/memsocket" }
network = { path = "../../network", features = ["fuzzing", "testing"] }
network-builder = { path  = "../../network/builder" }
storage-service = { path = "../../storage/storage-service" }
diem-transaction-builder = { path = "../../sdk/transaction-builder" }
diem-time-service = { path = "../../crates/diem-time-service", features = ["testing"] }
vm-genesis = { path = "../../language/tools/vm-genesis", features = ["fuzzing"] }

[features]
default = []
failpoints = ["fail/failpoints"]
fuzzing = ["vm-genesis", "proptest", "executor-test-helpers", "diem-config/fuzzing", "diem-mempool/fuzzing", "diem-types/fuzzing", "diem-proptest-helpers", "memsocket/fuzzing"]
