[package]
name = "bytecode-verifier-tests"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem bytecode verifier tests"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dev-dependencies]
petgraph = "0.5.1"
proptest = "0.10.1"

bytecode-verifier = { path = "../", version = "0.1.0" }
diem-types = { path = "../../../types", version = "0.1.0" }
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
invalid-mutations = { path = "../invalid-mutations", version = "0.1.0" }
move-core-types = { path = "../../move-core/types", version = "0.1.0" }
compiled-stdlib = { path = "../../stdlib/compiled",  version = "0.1.0" }
vm = { path = "../../vm", version = "0.1.0", features = ["fuzzing"] }

[features]
fuzzing = ["diem-types/fuzzing", "vm/fuzzing"]
