[package]
name = "schemadb"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
failure = { path = "../../common/failure_ext", package = "failure_ext" }

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"
rev = "4f8c6b3a48c7acb0c81f9bb91e7d8493b1c5a73e"

[dev-dependencies]
byteorder = "1.3.1"
tempfile = "3.0.6"
