[package]
name = "schemadb"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem schemadb"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.34"
once_cell = "1.4.1"
diem-config = { path = "../../config", version = "0.1.0" }
diem-metrics = { path = "../../common/metrics", version = "0.1.0" }
diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }

[dependencies.rocksdb]
version = "0.15.0"
default-features = false
features = ["lz4"]

[dev-dependencies]
byteorder = "1.3.4"
proptest = "0.10.1"
tempfile = "3.1.0"
diem-temppath = { path = "../../common/temppath", version = "0.1.0" }
