[package]
name = "scratchpad"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem scratchpad"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
itertools = "0.9.0"

diem-crypto = { path = "../../crypto/crypto", version = "0.1.0" }
diem-infallible = { path = "../../common/infallible", version = "0.1.0" }
diem-types = { path = "../../types", version = "0.1.0" }
diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }

[dev-dependencies]
proptest = "0.10.1"

[features]
default = []
fuzzing = ["diem-types/fuzzing"]
