[package]
name = "diem-json-rpc-client"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem JSONRPC client"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.34"
hex = "0.4.2"
reqwest = { version = "0.10.9", features = ["blocking", "json"], default_features = false }
serde = { version = "1.0.117", default-features = false }
serde_json = "1.0.60"
tokio = { version = "0.2.22", features = ["full"] }

diem-crypto = { path = "../../crypto/crypto", version = "0.1.0" }
lcs = { version = "0.1.0", package = "libra-canonical-serialization" }
diem-json-rpc-types  = { path = "../../json-rpc/types" }
diem-types = { path = "../../types", version = "0.1.0" }
diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }


[dev-dependencies]
warp = "0.2.5"
diem-config = { path = "../../config", version = "0.1.0" }


[features]
default = ["tls"]
tls = ["reqwest/native-tls"]
