[package]
name = "diem-trace"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem diem-trace"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
chrono = "0.4.19"
structopt = "0.3.21"
tokio = { version = "0.2.22", features = ["full"] }
serde_json = "1.0.60"
serde = "1.0.117"
anyhow = "1.0.34"
reqwest = { version = "0.10.9", features = ["blocking", "json"], default_features = false }
once_cell = "1.4.1"

diem-logger = { path = "../../common/logger", version = "0.1.0" }
diem-metrics = { path = "../metrics", version = "0.1.0" }
diem-workspace-hack = { path = "../workspace-hack", version = "0.1.0" }
