# This compose file supports running a faucet node that connects to the `validator-testnet`
# compose's json-rpc endpoint. This should be started after that compose has been started.
# The faucet can be accessed at 127.0.0.1:8000
#
# Additional notes:
# * Images can be found at https://hub.docker.com/r/diem/faucet/tags, obtain the latest tag and
# update below.
version: "3.8"
services:
    faucet:
        image: libra/faucet:devnet
        environment:
            AC_HOST: "172.16.1.3"
            AC_PORT: "8080"
            CFG_CHAIN_ID: "TESTING"
        networks:
            shared:
                ipv4_address: 172.16.1.2
        volumes:
            - type: volume
              source: diem-shared
              target: /opt/diem/var
        command: >
            /bin/bash -c "
                for i in {1..10}
                do
                    if [[ -s /opt/diem/var/mint.key ]]
                    then
                        /opt/diem/bin/diem-faucet \
                            --address 0.0.0.0 \
                            --port 8000 \
                            --chain-id TESTING \
                            --mint-key-file-path /opt/diem/var/mint.key \
                            --server-url http://172.16.1.3:8080
                        exit $$?
                    else
                        echo 'Validator has not populated mint.key yet. Is it running?'
                        sleep 1
                    fi
                done
                exit 1
              "
        ports:
            - "8000:8000"

networks:
    shared:
        external: true
        name: "diem-docker-compose-shared"

volumes:
    diem-shared:
        name: diem-shared
