# This compose file supports running a faucet node that connects to the `validator-testnet`
# compose's json-rpc endpoint. This should be started after that compose has been started.
# The faucet can be accessed at 127.0.0.1:8000
#
# Place the following files into the same directory:
# * mint.key (also known as the diem_root_key)
# * waypoint.txt
#
# Additional notes:
# * Images can be found at https://hub.docker.com/r/diem/faucet/tags, obtain the latest tag and
# update below.
version: "3.8"
services:
    faucet:
        image: libra/faucet:devnet
        environment:
            AC_HOST: "172.16.1.3"
            AC_PORT: "8080"
            CFG_CHAIN_ID: "TESTING"
        networks:
            shared:
                ipv4_address: 172.16.1.2
        volumes:
            - type: bind
              source: ./mint.key
              target: /opt/diem/etc/mint.key
        command: [
            "/opt/diem/bin/diem-faucet",
            "--address",
            "0.0.0.0",
            "--port",
            "8000",
            "--mint-key-file-path",
            "/opt/diem/etc/mint.key",
            "--server-url",
            "${AC_HOST:-172.16.1.3}"
        ]
        ports:
            - "8000:8000"
networks:
    shared:
        external: true
        name: "diem-docker-compose-shared"
