[package]
name = "debug-interface"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem debug interface"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
bytes = "1.0.1"
tokio = { version = "1.0.2", features = ["full"] }
reqwest = { version = "0.11.0", features = ["blocking", "json"], default_features = false }
warp = "0.3.0"

diem-logger = { path = "../logger", version = "0.1.0" }
diem-metrics = { path = "../metrics", version = "0.1.0" }
diem-workspace-hack = { path = "../workspace-hack", version = "0.1.0" }
