[package]
name = "shuffle-transaction-builder"
description = "Generated transaction builders"
version = "0.0.1"
authors = ["Diem Association <opensource@diem.com>"]
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
bcs = { git = "https://github.com/diem/bcs", rev = "30ce9f4ac51342d2fb4c04c4f5b40683d9652dc6" }
hex = "0.4.3"
once_cell = "1.7.2"
move-core-types = { path = "../../language/move-core/types" }
diem-types = { path = "../../types" }
thiserror = "1.0"
log = "0.4.14"
tokio = { version = "1.8.0", features = ["full", "time"] }
parking_lot = "0.11.1"

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
move-core-types = { path = "../../language/move-core/types" }
diem-workspace-hack = { path = "../../crates/diem-workspace-hack" }

[features]
default = []
#fuzzing = ["proptest", "proptest-derive", "move-core-types/fuzzing"]
