[package]
name = "cost_synthesis"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
rand = "0.6.5"
lazy_static = "1.3.0"

types = { path = "../../../types" }
vm = { path = "../" }
vm_runtime = { path = "../vm_runtime" }
vm_genesis = { path = "../vm_genesis" }
vm_cache_map = { path = "../vm_runtime/vm_cache_map" }
move_ir_natives = { path = "../../stdlib/natives" }

[dev-dependencies]
hex = "0.3.2"

[features]
default = ["vm_runtime/instruction_synthesis"]
