apiVersion: v1
kind: Pod
metadata:
  name: {pod_name}
  labels:
    app.kubernetes.io/name: forge
spec:
  restartPolicy: Never
  serviceAccountName: forge
  tolerations:
    - key: "forge"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
    - name: main
      image: {aws_account}.dkr.ecr.us-west-2.amazonaws.com/diem/forge:{forge_image_tag}
      imagePullPolicy: Always
      env: [{env_variables}]
      command:
        - sh
        - -c
        - |-
          set -ex
          bash /etc/forge/scripts/init_forge.sh
          timeout "{timeout_secs}" forge {extra_args}
      volumeMounts:
        - name: forge-init
          mountPath: /etc/forge/scripts
  volumes:
    - name: forge-init
      configMap:
        name: forge-init
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values: ["forge"]
          topologyKey: "kubernetes.io/hostname"
