[package]
name = "diem-writeset-generator"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Generating writesets used for incident management"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
structopt = "0.3.21"
tempfile = "3.2.0"
handlebars = "3.5.2"
serde = { version = "1.0.122", default-features = false }
serde_json = "1.0.61"
once_cell = "1.4.1"

diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
diem-crypto-derive = { path = "../../../crypto/crypto-derive", version = "0.1.0" }
diem-crypto = { path = "../../../crypto/crypto", version = "0.1.0" }
diem-types = { path = "../../../types", version = "0.1.0" }
compiled-stdlib = { path = "../../stdlib/compiled",  version = "0.1.0" }
stdlib = { path = "../../stdlib", version = "0.1.0" }
move-lang = { path = "../../move-lang", version = "0.0.1" }
bcs = "0.1.2"
diem-state-view = { path = "../../../storage/state-view", version = "0.1.0" }
diem-validator-interface = { path = "../diem-validator-interface", version = "0.1.0" }
diem-transaction-replay = { path = "../transaction-replay", version = "0.1.0" }
diemdb = { path = "../../../storage/diemdb", version = "0.1.0" }
diem-vm = { path = "../../diem-vm", version = "0.1.0" }
vm = { path = "../../vm", version = "0.1.0"}
move-vm-types = { path = "../../move-vm/types", version = "0.1.0" }
move-core-types = { path = "../../move-core/types", version = "0.1.0" }
move-vm-runtime = { path = "../../move-vm/runtime", version = "0.1.0" }
move-vm-test-utils = { path = "../../move-vm/test-utils", version = "0.1.0" }
