[package]
name = "diemdb"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem diemdb"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
arc-swap = "1.2.0"
byteorder = "1.4.3"
itertools = "0.10.0"
once_cell = "1.7.2"
num-derive = "0.3.3"
num-traits = "0.2.14"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
serde = "1.0.124"
thiserror = "1.0.37"

accumulator = { path = "../accumulator" }
bcs = { git = "https://github.com/diem/bcs", rev = "30ce9f4ac51342d2fb4c04c4f5b40683d9652dc6" }
diem-config = { path = "../../config" }
diem-crypto = { path = "../../crates/diem-crypto" }
diem-jellyfish-merkle = { path = "../jellyfish-merkle" }
diem-logger = { path = "../../crates/diem-logger" }
diem-metrics = { path = "../../crates/diem-metrics" }
diem-infallible = { path = "../../crates/diem-infallible" }
diem-proptest-helpers = { path = "../../crates/diem-proptest-helpers", optional = true }
diem-temppath = { path = "../../crates/diem-temppath", optional = true }
diem-types = { path = "../../types" }
diem-workspace-hack = { path = "../../crates/diem-workspace-hack" }
move-core-types = {path = "../../language/move-core/types"}

num-variants = { path = "../../crates/num-variants" }
schemadb = { path = "../schemadb" }
storage-interface = { path = "../storage-interface" }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
rand = "0.8.3"

diem-jellyfish-merkle = { path = "../jellyfish-merkle", features = ["fuzzing"] }
diem-proptest-helpers = { path = "../../crates/diem-proptest-helpers" }
diem-temppath = { path = "../../crates/diem-temppath" }
diem-types = { path = "../../types", features = ["fuzzing"] }

[features]
default = []
diemsum = []
fuzzing = ["proptest", "proptest-derive", "diem-proptest-helpers", "diem-temppath", "diem-crypto/fuzzing", "diem-jellyfish-merkle/fuzzing", "diem-types/fuzzing"]
