[package]
name = "serializer_tests"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dev-dependencies]
proptest = "0.9"
proptest-derive = "0.1.1"

[dev-dependencies.vm]
features = ["testing"]
path = "../"

[features]
testing = ["vm/testing"]
