[package]
name = "crash-handler"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem crash handler"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
backtrace = "0.3.55"
toml = "0.5.7"

diem-logger = { path = "../logger", version = "0.1.0" }
diem-workspace-hack = { path = "../workspace-hack", version = "0.1.0" }
serde = { version = "1.0.117", features = ["derive"] }
