[package]
name = "transaction-builder-generated"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Generated transaction builders"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
edition = "2018"

[dependencies]
once_cell = "1.6.0"
serde = { version = "1.0.123", features = ["derive"] }

compiled-stdlib = { path = "../../language/diem-framework/compiled" }
bcs = "0.1.2"
move-core-types = { path = "../../language/move-core/types" }
diem-types = { path = "../../types" }
diem-workspace-hack = { path = "../../common/workspace-hack" }

proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
diem-proptest-helpers = { path = "../../common/proptest-helpers", optional = true }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "diem-proptest-helpers", "move-core-types/fuzzing"]
