[package]
name = "diem-metrics-core"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem diem-metrics-core"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
diem-workspace-hack = { path = "../workspace-hack", version = "0.1.0" }
prometheus = { version = "0.11.0", default-features = false }
