[package]
name = "diem-vault-client"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
repository = "https://github.com/diem/diem"
description = "Diem's Restful Vault Client"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
base64 = "0.13.0"
chrono = "0.4.19"
once_cell = "1.4.1"
proptest = { version = "0.10.1", optional = true }
native-tls = "0.2.7"
serde = { version = "1.0.122", features = ["derive"], default-features = false }
serde_json = "1.0.61"
thiserror = "1.0.23"
ureq = { version = "1.5.4", features = ["json", "native-tls"], default-features = false }

diem-crypto = { path = "../../../crypto/crypto", version = "0.1.0" }
diem-proptest-helpers = { path = "../../../common/proptest-helpers", version = "0.1.0", optional = true }
diem-types = { path = "../../../types", version = "0.1.0", optional = true }
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }

[dev-dependencies]
proptest = "0.10.1"

diem-proptest-helpers = { path = "../../../common/proptest-helpers", version = "0.1.0" }
diem-types = { path = "../../../types", version = "0.1.0", features = ["fuzzing"] }

[features]
fuzzing = ["proptest", "diem-proptest-helpers", "diem-types"]
