[base]
peer_id = "<UNUSED>"
data_dir_path = "<USE_TEMP_DIR>"
trusted_peers_file = "/opt/libra/etc/trusted_peers.config.toml"
peer_keypairs_file = "/opt/libra/etc/peer_keypairs.config.toml"
node_sync_batch_size = 1000
node_sync_retries = 3
node_sync_channel_buffer_size = 10
node_async_log_chan_size = 256

[metrics]
dir = ""
collection_interval_ms = 1000
push_server_addr = ""

[execution]
address = "localhost"
port = 59622
testnet_genesis = false
genesis_file_location = "/opt/libra/etc/genesis.blob"

[admission_control]
address = "0.0.0.0"
admission_control_service_port = 30307
need_to_check_mempool_before_validation = false

[debug_interface]
admission_control_node_debug_port = 30306
storage_node_debug_port = 49125
secret_service_node_debug_port = 50316
metrics_server_port = 14297
address = "0.0.0.0"

[storage]
address = "localhost"
port = 35647
dir = "/opt/libra/data"

[network]
seed_peers_file = "/opt/libra/etc/seed_peers.config.toml"
listen_address = "/ip4/0.0.0.0/tcp/30303"
advertised_address = "/ip4/SELF_IP/tcp/30303"
discovery_interval_ms = 1000
connectivity_check_interval_ms = 5000
enable_encryption_and_authentication = true

[consensus]
max_block_size = 100
proposer_type = "rotating_proposer"
contiguous_rounds = 2

[mempool]
broadcast_transactions = true
shared_mempool_tick_interval_ms = 50
shared_mempool_batch_size = 100
shared_mempool_max_concurrent_inbound_syncs = 100
capacity = 10000000
capacity_per_user = 100
sequence_cache_capacity = 1000
system_transaction_timeout_secs = 86400
system_transaction_gc_interval_ms = 180000
mempool_service_port = 59620
address = "localhost"

[log_collector]
is_async = true
use_std_output = true

[vm_config]
  [vm_config.publishing_options]
  type = "Locked"
  whitelist = [
      "587b2d840dab19bd0f7412e1ca9fc3e50c0d790ca97e8bc5437934faa5c29a94",
      "59c9d8d9e4d2b2eb5b60b2d19cbd33b407c0c2c164091947584ac48687593ecf",
      "25e78410bf55d2f232d321722f1be3e8ba82a1b7198a79bc9c878bc4270773dd",
      "e5cf5c50f35e09564df21d1cdfdf03cb393a837166e1c5237eb2d8b1a884abe2"
  ]

[secret_service]
address = "localhost"
secret_service_port = 59618
