name: ci-test

on:
  push:
    branches: [auto, gha-test-*]
  pull_request:
    branches: [main, master, release-*, gha-test-*]

jobs:
  prepare:
    runs-on: ubuntu-latest
    continue-on-error: false
    outputs:
      changes-target-branch: ${{ steps.changes.outputs.changes-target-branch }}
      changes-base-githash: ${{ steps.changes.outputs.changes-base-githash }}
      changes-pull-request-number: ${{ steps.changes.outputs.changes-pull-request-number }}
      test-rust: ${{ steps.rust-changes.outputs.changes-found }}
      test-dev-setup: ${{ steps.dev-setup-sh-changes.outputs.changes-found }}
      test-website-build: ${{ steps.website-changes.outputs.changes-found }}
      test-non-rust-lint: ${{ steps.non-rust-lint-changes.outputs.changes-found }}
      max-threads: "16"
    steps:
      - uses: actions/checkout@v2
        with:
          # This ensures that the tip of the PR is checked out instead of the merge between the base ref and the tip
          # On `push` this value will be empty and will "do-the-right-thing"
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 #get all the history!!!
      - name: Git Hooks and Checks
        run: ./scripts/git-checks.sh
      - id: changes
        name: determine changes
        uses: ./.github/actions/changes
        with:
          workflow-file: ci-test.yml
      - id: rust-changes
        name: find rust/cargo changes.
        uses: ./.github/actions/matches
        with:
          pattern: '^documentation\|^docker\|^scripts'
          invert: "true"
      - id: non-rust-lint-changes
        name: find shell/dockerfile changes
        uses: ./.github/actions/matches
        with:
          pattern: 'Dockerfile$\|.sh$'
      - id: dev-setup-sh-changes
        name: find dev-setup.sh/base docker image changes
        uses: ./.github/actions/matches
        with:
          pattern: '^.github\|docker/ci\|scripts/dev_setup.sh'
      - id: website-changes
        name: find website changes.
        uses: ./.github/actions/matches
        with:
          pattern: "^documentation"

  dev-setup-sh-test:
    runs-on: ubuntu-latest-xl
    continue-on-error: false
    timeout-minutes: 30
    needs: prepare
    if: ${{ needs.prepare.outputs.test-dev-setup == 'true' }}
    strategy:
      matrix:
        target_os: [alpine, arch, centos, github]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: build image with dev-setup.sh
        run: docker build -f docker/ci/${{ matrix.target_os }}/Dockerfile -t libra/build_environment:test .

  non-rust-lint:
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 5
    needs: prepare
    if: ${{ needs.prepare.outputs.test-non-rust-lint == 'true'  }}
    container:
      image: libra/build_environment:github-1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: shell lints
        run: |
          shellcheck scripts/dev_setup.sh && \
          shellcheck scripts/dockerhub_prune.sh && \
          shellcheck .github/actions/changes/get_pr_info.sh && \
          shellcheck docker/build_push.sh && \
          shellcheck docker/dockerhub_to_novi_ecr.sh
      - name: docker lints
        run: |
          hadolint docker/ci/github/Dockerfile && \
          hadolint docker/ci/arch/Dockerfile && \
          hadolint docker/ci/alpine/Dockerfile && \
          hadolint docker/ci/centos/Dockerfile

  lint:
    runs-on: ubuntu-latest-xl
    timeout-minutes: 30
    continue-on-error: false
    needs: prepare
    if: ${{ needs.prepare.outputs.test-rust == 'true' }}
    container:
      image: libra/build_environment:github-1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/build-setup
      - name: cargo lint
        run: cargo x lint
      - name: cargo clippy
        run: cargo xclippy --workspace --all-targets
      - name: cargo clippy tcb
        run: cargo xclippy --members lec --members lsr --members key-manager
      - name: cargo fmt
        run: cargo xfmt --check
      - uses: ./.github/actions/build-teardown

  unit-test:
    runs-on: ubuntu-latest-xl
    timeout-minutes: 40
    continue-on-error: false
    needs: prepare
    if: ${{ needs.prepare.outputs.test-rust == 'true' }}
    container:
      image: libra/build_environment:github-1
    env:
      max_threads: ${{ needs.prepare.outputs.max-threads }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 #get all the history!!!
      - uses: ./.github/actions/build-setup
      - name: run unit tests
        run: cargo x test --jobs ${max_threads} --unit --changed-since "origin/$TARGET_BRANCH"
        env:
          TARGET_BRANCH: ${{ needs.prepare.outputs.changes-target-branch }}
      - uses: ./.github/actions/build-teardown

  e2e-test:
    runs-on: ubuntu-latest-xl
    timeout-minutes: 40
    continue-on-error: false
    needs: prepare
    if: ${{ needs.prepare.outputs.test-rust == 'true' }}
    container:
      image: libra/build_environment:github-1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/build-setup
      - name: run e2e tests
        run: cargo x test --package smoke-test -- --test-threads 2 --nocapture
      - uses: ./.github/actions/build-teardown

  crypto-unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: false
    needs: prepare
    if: ${{ needs.prepare.outputs.test-rust == 'true' }}
    container:
      image: libra/build_environment:github-1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/build-setup
      - name: run crypto unit tests
        run: |
          cd crypto/crypto
          $CARGO $CARGOFLAGS test --features='vanilla-u64' --no-default-features
          $CARGO $CARGOFLAGS test --features='vanilla-u32' --no-default-features
      - uses: ./.github/actions/build-teardown

  # Compile (but don't run) the benchmarks, to insulate against bit rot
  build-benchmarks:
    runs-on: ubuntu-latest-xl
    timeout-minutes: 30
    continue-on-error: false
    needs: prepare
    if: ${{ needs.prepare.outputs.test-rust == 'true' }}
    container:
      image: libra/build_environment:github-1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/build-setup
      - name: build benchmarks
        run: cargo x bench --no-run
      - uses: ./.github/actions/build-teardown

  build-dev:
    runs-on: ubuntu-latest-xl
    timeout-minutes: 30
    continue-on-error: false
    needs: prepare
    if: ${{ needs.prepare.outputs.test-rust == 'true' }}
    container:
      image: libra/build_environment:github-1
    env:
      max_threads: ${{ needs.prepare.outputs.max-threads }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/build-setup
      - run: cargo xcheck -j ${max_threads} --members production
      - run: cargo xcheck -j ${max_threads} --workspace --all-targets
      - run: |
          rustup target add powerpc-unknown-linux-gnu
          cargo xcheck -j ${max_threads} -p transaction-builder -p move-vm-types --target powerpc-unknown-linux-gnu
      - uses: ./.github/actions/build-teardown
