name: Dependency Notifier

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  annotate-dep-summaries:
    runs-on: ubuntu-latest
    name: Annotate PRs with dependency summary changes
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: fetch base ref
        id: fetch-base-ref
        uses: ./.github/actions/pr-base-ref
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: checkout base ref
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.fetch-base-ref.outputs.ref }}
          path: libra-base

      - name: generate new summaries
        run: |
          set +e
          cargo run -p x -- generate-summaries

      - name: diff LSR summary
        id: verify-lsr
        run: |
          if [[ ! -e libra-base/summaries/summary-lsr.toml ]]; then
            # handle case of missing base summary by reporting no diff
            echo "::set-output name=diff::"
            exit 0
          fi
          output="$(cargo run -p x -- diff-summary libra-base/summaries/summary-lsr.toml target/summaries/summary-lsr.toml)"
          echo "${output}"
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}"
          echo "::set-output name=diff::${output}"
      - name: diff LEC summary
        id: verify-lec
        run: |
          if [[ ! -e libra-base/summaries/summary-lec.toml ]]; then
            # handle case of missing base summary by reporting no diff
            echo "::set-output name=diff::"
            exit 0
          fi
          output="$(cargo run -p x -- diff-summary libra-base/summaries/summary-lec.toml target/summaries/summary-lec.toml)"
          echo "${output}"
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}"
          echo "::set-output name=diff::${output}"
      - name: diff release summary
        id: verify-release
        run: |
          if [[ ! -e libra-base/summaries/summary-release.toml ]]; then
            # handle case of missing base summary by reporting no diff
            echo "::set-output name=diff::"
            exit 0
          fi
          output="$(cargo run -p x -- diff-summary libra-base/summaries/summary-release.toml target/summaries/summary-release.toml)"
          echo "${output}"
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}"
          echo "::set-output name=diff::${output}"

      - name: annotate PR with LSR diff
        if: ${{ steps.verify-lsr.outputs.diff }}
        uses: ./.github/actions/comment
        with:
          comment: |
            **LSR dependency change summary**:
            ```
            ${{ steps.verify-lsr.outputs.diff }}
            ```
          tag: lsr-summary
          delete-older: true
      - name: annotate PR with LEC diff
        if: ${{ steps.verify-lec.outputs.diff }}
        uses: ./.github/actions/comment
        with:
          comment: |
            **LEC dependency change summary**:
            ```
            ${{ steps.verify-lec.outputs.diff }}
            ```
          tag: lec-summary
          delete-older: true
      - name: annotate PR with release diff
        if: ${{ steps.verify-release.outputs.diff }}
        uses: ./.github/actions/comment
        with:
          comment: |
            **release binaries dependency change summary**:
            ```
            ${{ steps.verify-release.outputs.diff }}
            ```
          tag: release-summary
          delete-older: true
      - name: label PR if TCB changed
        if: ${{ steps.verify-lsr.outputs.diff || steps.verify-lec.outputs.diff }}
        uses: ./.github/actions/labels
        with:
          add: tcb-deps-changed
      - name: label PR if release changed
        if: ${{ steps.verify-lsr.outputs.diff || steps.verify-lec.outputs.diff || steps.verify-release.outputs.diff }}
        uses: ./.github/actions/labels
        with:
          add: deps-changed

      - name: fail PR if summaries are not updated
        run: |
          lsr_diff="$(cargo run -p x -- diff-summary summaries/summary-lsr.toml target/summaries/summary-lsr.toml)"
          lec_diff="$(cargo run -p x -- diff-summary summaries/summary-lec.toml target/summaries/summary-lec.toml)"
          release_diff="$(cargo run -p x -- diff-summary summaries/summary-release.toml target/summaries/summary-release.toml)"

          if [[ -n "${lsr_diff}" || -n "${lec_diff}" || -n "${release_diff}" ]]; then
            echo "Summaryies are not updated. You can update summaries with:"
            echo "'cargo run -p x -- generate-summaries' and copying the changed summaries"
            echo "from target/summaries to summaries."
            exit 1
          fi
