name: (hyperjump) request-review

on:
  repository_dispatch:
    types: [request-review]

jobs:
  labels:
    runs-on: ubuntu-latest
    name: (hyperjump) request-review
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: request review
        uses: diem/actions/hyperjump-request-review@faa14430e68d54a269628f385e69a207e4e413d5
        with:
          github-token: ${{ secrets.HYPERJUMP_TOKEN }}
          number: ${{ github.event.client_payload.number }}
          users: ${{ join(github.event.client_payload.users) }}
          teams: ${{ join(github.event.client_payload.teams) }}
