name: (hyperjump) labels

on:
  repository_dispatch:
    types: [labels]

jobs:
  labels:
    runs-on: ubuntu-latest
    name: (hyperjump) labels
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: labels
        uses: diem/actions/hyperjump-labels@26629aba5897746c40697c786d71635767f87cda
        with:
          github-token: ${{ secrets.HYPERJUMP_TOKEN }}
          number: ${{ github.event.client_payload.number }}
          add: ${{ join(github.event.client_payload.add) }}
          remove: ${{ join(github.event.client_payload.remove) }}
