name: (hyperjump) comment

on:
  repository_dispatch:
    types: [comment]

jobs:
  comment:
    runs-on: ubuntu-latest
    name: (hyperjump) comment
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: comment
        uses: diem/actions/hyperjump-comment@faa14430e68d54a269628f385e69a207e4e413d5
        with:
          github-token: ${{ secrets.HYPERJUMP_TOKEN }}
          number: ${{ github.event.client_payload.number }}
          comment: ${{ github.event.client_payload.comment }}
          tag: ${{ github.event.client_payload.tag }}
          delete-older: ${{ github.event.client_payload.delete_older }}
